
package com.modeln.ws.remoteact;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.jws.HandlerChain;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(
        name = "MnRemoteActWebSvcService",
        targetNamespace = "http://remoteact.ws.modeln.com",
        wsdlLocation = "http://pdjbpringuey:7001/webservices/platform/MnRemoteActWebSvc?wsdl")
@HandlerChain(file="handler-chain.xml")
public class MnRemoteActWebSvcService
    extends Service
{


    private final static URL MNREMOTEACTWEBSVCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.modeln.ws.remoteact.MnRemoteActWebSvcService.class.getName());

    static {

        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.modeln.ws.remoteact.MnRemoteActWebSvcService.class.getResource(".");
            url = new URL(baseUrl,System.getProperty("Wsurl"));
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+System.getProperty("Wsurl")+"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MNREMOTEACTWEBSVCSERVICE_WSDL_LOCATION = url;
    }

    public MnRemoteActWebSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MnRemoteActWebSvcService() {
        super(MNREMOTEACTWEBSVCSERVICE_WSDL_LOCATION, new QName("http://remoteact.ws.modeln.com", "MnRemoteActWebSvcService"));
    }

    /**
     * 
     * @return
     *     returns MnRemoteActWebSvcPortType
     */
    @WebEndpoint(name = "MnRemoteActWebSvcPort")
    public MnRemoteActWebSvcPortType getMnRemoteActWebSvcPort() {
        return super.getPort(new QName("http://remoteact.ws.modeln.com", "MnRemoteActWebSvcPort"), MnRemoteActWebSvcPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MnRemoteActWebSvcPortType
     */
    @WebEndpoint(name = "MnRemoteActWebSvcPort")
    public MnRemoteActWebSvcPortType getMnRemoteActWebSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://remoteact.ws.modeln.com", "MnRemoteActWebSvcPort"), MnRemoteActWebSvcPortType.class, features);
    }

}
