
package com.modeln.ws.remoteact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.modeln.ws.remoteact.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MnRemoteActWebSvcPortType", targetNamespace = "http://remoteact.ws.modeln.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MnRemoteActWebSvcPortType {


    /**
     * 
     * @param outputLogs
     * @param testResult
     * @param errorLogs
     * @param act
     */
    @WebMethod(action = "http://remoteact.ws.modeln.com/types")
    @RequestWrapper(localName = "executeAct", targetNamespace = "http://remoteact.ws.modeln.com/types", className = "com.modeln.ws.remoteact.types.ExecuteAct")
    @ResponseWrapper(localName = "executeActResponse", targetNamespace = "http://remoteact.ws.modeln.com/types", className = "com.modeln.ws.remoteact.types.WSTestResultResult")
    public void executeAct(
        @WebParam(name = "act", targetNamespace = "")
        String act,
        @WebParam(name = "outputLogs", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> outputLogs,
        @WebParam(name = "errorLogs", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> errorLogs,
        @WebParam(name = "testResult", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> testResult);

}
